article/urls.py
from django.urls import path

from .views.api import article_creation, article_detail, set_favorite
from .views.page import page_article_creation, page_article_detail, page_article_edit

app_name = "article"


urlpatterns = [
    # Pages
    path("new/", page_article_creation, name="new"),
    path("edit/<int:pk>/", page_article_edit, name="edit-page"),
    path("<int:pk>/", page_article_detail, name="detail"),
    # API
    path("api/", article_creation, name="api-new"),
    path("api/<int:pk>/", article_detail, name="api-detail"),
    path("api/<int:pk>/favorite/", set_favorite, name="api-set-favorite"),
]

common/urls.py
from django.urls import path

from .views import detail_comment, link_detail, link_list, list_comment, report, tag

urlpatterns = [
    path(
        "api/comment/<int:pk>",
        detail_comment,
        name="api-detail-comment",
    ),
    path(
        "api/comment/<int:pk>/<str:content_type>",
        list_comment,
        name="api-list-comment",
    ),
    path(
        "api/links/<str:content_type>",
        link_list,
        name="api-link-list",
    ),
    path(
        "api/link/<int:pk>",
        link_detail,
        name="api-link-detail",
    ),
    path("api/report/<int:pk>/<str:content_type>", report, name="api-report"),
    path(
        "tag/<int:pk>/",
        tag,
        name="tag-detail",
    ),
]

elisasrecipe/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path

from .views.api import FeedSearchView, FeedView, health, search
from .views.page import about, cookie, index, policy, terms


def health(request):
    return JsonResponse({"status": "ok"})


urlpatterns = [
    path("admin/", admin.site.urls),
    path("health/", health, name="health"),
    # path("", include("django_backblaze_b2.urls")),
]
if settings.DEBUG:
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

urlpatterns += i18n_patterns(
    path("", index, name="home"),
    path("cookie/", cookie, name="cookie"),
    path("policy/", policy, name="policy"),
    path("terms/", terms, name="terms"),
    path("about/", about, name="about"),
    path("recipes/", about, name="page-recipes"),
    path("articles/", about, name="page-articles"),
    path("authors/", about, name="page-authors"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("feed/search", FeedSearchView.as_view(), name="feed-search"),
    path("api/search", search, name="api-search"),
    path("", include("account.urls")),
    path("article/", include("article.urls")),
    path("", include("common.urls")),
    path("recipe/", include("recipe.urls")),
)

recipe/urls.py
from django.urls import path
from recipe.views.api import ingredient_detail  # recipe_creation,
from recipe.views.api import (
    recipe_creation,
    ingredient_list,
    recipe_edit,
    search_recipes,
    set_favorite,
    set_rating,
    step_detail,
    step_list,
)

from .views.page import (
    page_edit_recipe,
    page_recipe_creation,
    page_recipe_detail,
    page_recipes,
    page_search_recipes,
)

app_name = "recipe"

urlpatterns = [
    # Pages
    path("", page_recipes, name="list"),
    path("new/", page_recipe_creation, name="new"),
    path("<int:pk>/", page_recipe_detail, name="detail"),
    path("<int:pk>/edit/", page_edit_recipe, name="edit"),
    # path("search/", page_search_recipes, name="search"),
    # API
    # path("api/search/", search_recipes, name="api-search"),
    path("api/list", recipe_creation, name="api-list"),
    path("api/<int:pk>/", recipe_edit, name="api-detail"),
    path("api/<int:pk>/rating/", set_rating, name="api-rating"),
    path("api/<int:pk>/favorite/", set_favorite, name="api-favorite"),
    path("api/ingredient/", ingredient_list, name="api-ingredient-list"),
    path("api/ingredient/<int:pk>/", ingredient_detail, name="api-ingredient-detail"),
    path("api/step/", step_list, name="api-step-list"),
    path("api/step/<int:pk>/", step_detail, name="api-step-detail"),
]

recipe/views/api.py
import json

from common.models import Image, Rate, Tag
from django.contrib.postgres.search import (
    SearchHeadline,
    SearchQuery,
    SearchRank,
    SearchVector,
    TrigramSimilarity,
)
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from recipe.forms import RecipeForm, RecipeIngredientForm, RecipeStepForm
from recipe.models import Recipe, RecipeIngredient, RecipeStep


def recipe_creation(request):
    if request.method == "POST":
        return "pas que des arnimols"
    return HttpResponse("Method not allowed", status=405)


def recipe_edit(request, pk):
    print(request.POST)
    if request.method == "POST":
        recipe = Recipe.objects.get(pk=pk)
        form = RecipeForm(request.POST, instance=recipe)
        recipe_write(form, recipe, request)
        return redirect(reverse("recipe:detail", args=[pk]))
    if request.method == "DELETE":
        recipe = Recipe.objects.get(pk=pk)
        recipe.delete()
        return redirect(reverse("home"))
    return HttpResponse("Method not allowed", status=405)


def recipe_write(form, recipe, request):
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        if form.is_published:
            recipe.is_draft = False
    else:
        # TODO:
        # tell user something went wrong
        print(form.errors)
        return HttpResponse("the form is not valid", status=410)
    form.save()
    recipe.tags.clear()
    if request.POST.get("tags"):
        tags = json.loads(request.POST.get("tags"))
        for tag in tags:
            tag, _ = Tag.objects.get_or_create(name=tag.get("value"))
            recipe.tags.add(tag)
    print("recipe image", recipe.image, recipe.id)
    if "image" in request.FILES:
        print(request.FILES["image"])
        image = Image(image=request.FILES["image"])
        image.save()
        recipe.image = image
    else:
        print("recipe.image", recipe.image)
        if not recipe.image:
            print("no image")
            image = Image.objects.get(pk=15)
            recipe.image = image
    recipe.save()
    return recipe.id


def ingredient_list(request):
    recipe = Recipe.objects.get(id=request.POST.get("recipe"))
    if request.method == "POST":
        form = RecipeIngredientForm(request.POST)
        form.recipe_id = recipe.id
        if form.is_valid():
            form.save()
            print("form.saved")
        else:
            print(form.errors)
        ingredients = [
            ingredient
            for ingredient in RecipeIngredient.objects.filter(recipe=recipe.id)
        ]
        return render(
            request,
            "patterns/components/ingredient_list/ingredient_list.html",
            {"ingredients": ingredients, "recipe": recipe},
        )


def ingredient_detail(request, pk):
    print(1)
    if request.method == "DELETE":
        print(2)
        ingredient = get_object_or_404(RecipeIngredient, pk=pk)
        ingredient.delete()
        ings = [
            ingredient
            for ingredient in RecipeIngredient.objects.filter(recipe=ingredient.recipe)
        ]
        print(ings)

        return render(
            request,
            "patterns/components/ingredient_list/ingredient_list.html",
            {"ings": ings, "recipe": ingredient.recipe},
        )


def step_list(request):
    print(request.POST)
    recipe = Recipe.objects.get(id=request.POST.get("recipe"))
    if request.method == "POST":
        form = RecipeStepForm(request.POST)
        print(form.errors)
        if form.is_valid():
            step = form.save(commit=False)
            if "image" in request.FILES:
                image = Image(image=request.FILES["image"])
                image.save()
                print("image saved")
                step.image = image

            step.recipe = recipe
            step.save()
        steps = [step for step in RecipeStep.objects.filter(recipe=recipe)]
        return render(
            request,
            "patterns/components/step_list/step_list.html",
            {"steps": steps, "recipe": recipe},
        )


def step_detail(request, pk):
    if request.method == "DELETE":
        step = get_object_or_404(RecipeStep, pk=pk)
        step.delete()
        steps = [step for step in RecipeStep.objects.filter(recipe=step.recipe)]

        return render(
            request,
            "components/step_list.html",
            {
                "steps": steps,
            },
        )


def set_favorite(request, pk):
    user = request.user
    recipe = get_object_or_404(Recipe, pk=pk)
    if recipe in user.favorite_recipes.all():
        print("remove")
        user.favorite_recipes.remove(recipe)
        is_favorite = False
    else:
        user.favorite_recipes.add(recipe)
        is_favorite = True
        print("add")
    return render(
        request,
        "is_favorite.html",
        {"recipe": recipe, "is_favorite": is_favorite},
    )


def set_rating(request, pk):
    if request.htmx:
        recipe = get_object_or_404(Recipe, pk=pk)
        rate = recipe.rates.filter(user=request.user).first()
        if rate:
            rate.value = request.POST.get("rate")
            rate.save()
        else:
            rate = Rate.objects.create(
                user=request.user, content_object=recipe, value=request.POST.get("rate")
            )
    return render(request, "patterns/components/rate/rate.html", {"rate": rate.value})


def search_recipes(request):
    if request.htmx:
        search_query = request.POST.get("search")
        vector = SearchVector("title", "description", "instructions")
        query = SearchQuery(search_query)
        search_headline = SearchHeadline("title", query)
        recipes = (
            Recipe.objects.annotate(
                rank=SearchRank(vector, query),
                similarity=TrigramSimilarity("title", search_query),
            )
            .annotate(headline=search_headline)
            .filter(rank__gte=0.00001)
            .order_by("-rank")
        )
        return render(request, "recipe_list.html", {"recipes": recipes})

recipe/views/page.py
from common.forms import CommentForm
from common.models import Tag
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Q
from django.shortcuts import get_object_or_404, render

# from easyaudit.models import CRUDEvent
from recipe.forms import RecipeForm, RecipeStepForm
from recipe.models import Ingredient, Recipe, RecipeIngredient


@login_required
def page_recipe_creation(request):
    form = RecipeForm()
    ingredient_names = [ingredient.name for ingredient in Ingredient.objects.all()]
    tags = Tag.objects.all()
    return render(
        request,
        "patterns/pages/list_recipe/new_recipe.html",
        {
            "form": form,
            "recipeStepForm": RecipeStepForm(),
            "recipe": None,
            "ingredient_names": ingredient_names,
            "tag_list": [tag.name for tag in tags],
        },
    )


def page_recipe_detail(request, pk):
    user = request.user
    recipe = get_object_or_404(Recipe, pk=pk)
    # crud_events = CRUDEvent.objects.filter(
    #     content_type__model="recipe", object_id=recipe.id
    # )
    # request_events = RequestEvent.objects.filter(
    # content_type__model="recipe", object_id=recipe.id
    # )
    # print("request_events")
    # print(request_events)
    # print("crud_events")
    # print(crud_events)
    if user.is_authenticated:
        is_favorite = recipe in user.favorite_recipes.all()
        rate = recipe.rates.filter(user=request.user).first()
        if rate:
            rate = rate.value or 3
        else:
            rate = False
    else:
        is_favorite = False
        rate = False

    rate_average = recipe.rates.aggregate(Avg("value"))["value__avg"]

    ingredients = RecipeIngredient.objects.filter(recipe=recipe)
    comments = recipe.comments.order_by("-created_at")
    steps = recipe.steps.all()
    number_of_rate_given = recipe.rates.count()
    return render(
        request,
        "detail_recipe.html",
        {
            "recipe": recipe,
            "is_favorite": is_favorite,
            "comment_form": CommentForm(),
            "ingredients": ingredients,
            "steps": steps,
            "comments": comments,
            "rate": rate,
            "given_rate": {
                "rate_average": rate_average,
                "number_of_rate_given": number_of_rate_given,
            },
        },
    )


def page_edit_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    ings = recipe.ingredients.all()

    form = RecipeForm(instance=recipe)
    tags = Tag.objects.all()
    return render(
        request,
        "patterns/pages/list_recipe/new_recipe.html",
        {
            "form": form,
            "ings": ings,
            "recipe": recipe,
            "recipeStepForm": RecipeStepForm(),
            "create": False,
            "tag_list": [tag.name for tag in tags],
        },
    )


def page_recipes(request):
    recipes = Recipe.objects.filter(is_draft=False)
    return render(
        request,
        "recipes.html",
        {
            "recipes": recipes,
        },
    )


def page_search_recipes(request):
    print(request.POST)
    if request.htmx:
        # include
        search_query = request.POST.get("search")
        recipes = Recipe.objects.filter(
            # Q(title__unaccent__icontains=search_query)
            # | Q(description__search=search_query)
            Q(title__icontains=search_query)
            | Q(description__icontains=search_query)
        )
        return render(request, "recipe_list.html", {"recipes": recipes})

app/recipe/templates/patterns/pages/new_recipe/new_recipe.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block extra_head %}
    {% include "components/quill_import.html" %}
    <script src="{% static 'htmx.min.js' %}" defer></script>
    <script src={% static "tagify/tagify" %}></script>
    <script src={% static "tagify/tagify.polyfills.min.js"%}></script>
    <link href="{% static "tagify/tagify.css" %}" rel="stylesheet" type="text/css" />
{% endblock extra_head %}
{% block content %}
    {% include "navbar.html" %}
    <section class="w-1/2 mx-auto bg-orange-50 px-10 pb-10 rounded-lg">
        <form id="top-form"
              class="-mt-10"
              method="post"
              enctype="multipart/form-data"
              {% if create %} action="{% url "recipe:api-new" %}" {% else %} action="{% url "recipe:api-edit" pk=recipe.id %}" {% endif %}>
            {% csrf_token %}
            <input type="hidden" name=recipe value={{ recipe.id }} />
            <div class="flex items-end ml-20">
                <img src="{% static 'notes.svg' %}"
                     alt="Profile Picture"
                     class="w-60 h-60 inline" />
                <div class=" inline text-orange-700 ">
                    {% if create %}
                        <p class="text-4xl capitalize font-bold underline">New Recipe</p>
                        <p class=" -mt-1.5 text-orange-300">creation of a new recipe</p>
                    {% else %}
                        <p class="text-4xl capitalize font-bold underline">Edit Recipe</p>
                        <p class=" -mt-1.5 text-orange-300">Make your recipe even better</p>
                    {% endif %}
                </div>
            </div>
            <label for={{ form.title.name }} class="flex mt-10">
                Name<span class="text-red-600">*</span>:
                {% include "patterns/components/icons/help/help.html" with help_text="Just the way you want to call it?" %}
            </label>
            <input type="text" name={{ form.title.name }} data-test="title" class="rounded-lg bg-orange-200 focus:ring-0 border-0 w-full" required placeholder="{{ form.title.label }}" {% if recipe.title %}value="{{ recipe.title }}"{% endif %} />
            <label for={{ form.title.category }} class="flex mt-5">
                Category:
                {% include "patterns/components/icons/help/help.html" with help_text="What is the category of your recipe?" %}
            </label>
            <select name="category"
                    id="{{ form.category.id_for_label }}"
                    class="bg-orange-200 capitalize  text-gray-900 text-sm rounded-lg focus:ring-0 border-0 block w-full p-2.5"
                    data-test="category">
                {% for value in form.category %}
                    <option value="{{ value.data.value }}"
                            class="capitalize"
                            {% if value.data.value == form.category.value %}selected{% endif %}>
                        {{ value.data.value }}
                    </option>
                {% endfor %}
            </select>
            <label for={{ form.description.name }} class="flex mt-5">
                Description:
                {% include "patterns/components/icons/help/help.html" with help_text="A Description to descibe what is you recipe about" %}
            </label>
            <textarea type="textarea" name={{ form.description.name }} data-test="description" class=" bg-orange-200 capitalize  text-gray-900 text-sm rounded-lg focus:ring-0 border-0 block w-full p-2.5" placeholder="Please enter a desciption">{% if recipe.description %}{{ recipe.description }}{% endif%}</textarea>
            <label for={{ form.image.name }} class="flex mt-5">
                Image:
                {% include "patterns/components/icons/help/help.html" with help_text="this is going to be the background image of the recipe" %}
            </label>
            {% if recipe.image.url %}
                <img src="{{ recipe.image.url }}"
                     alt="recipe image"
                     class="w-60 h-60 inline" />
            {% endif %}
            <input type="file" name="image" accept="image/*" data-test="image-desc">
            <label for={{ form.recipe_origin.name }} class="flex mt-5 ">
                Origin:
                {% include "patterns/components/icons/help/help.html" with help_text="Just in case if you know where the recipe come from it's' always nice to have a bit of background but if you don't that's fine just dont add anything" %}
            </label>
            <select name="recipe_origin"
                    id="{{ form.recipe_origin.id_for_label }}"
                    class="bg-orange-200 capitalize text-gray-900 text-sm rounded-lg focus:ring-0 border-0 block w-full p-2.5"
                    data-test="origin">
                <option value="" {% if not form.recipe_origin.value %}selected{% endif %}></option>
                {% for value in form.recipe_origin %}
                    <option value="{{ value.data.value }}"
                            class="capitalize"
                            {% if value.data.value == form.recipe_origin.value %}selected{% endif %}>
                        {{ value.data.value }}
                    </option>
                {% endfor %}
            </select>
            <label for={{ form.recipe_origin.name }} class="flex mt-5 ">
                Duration:
                {% include "patterns/components/icons/help/help.html" with help_text="How much time is it going to take" %}
            </label>
            <div class="flex">
                <input type="number" name={{ form.duration.name }} value={{ form.duration.value }} class=" bg-orange-200 capitalize  text-gray-900 text-sm rounded-lg focus:ring-0 border-0 block  p-2.5" min=0 data-test="duration-input" />
                <select name={{ form.duration_scale.name }} id="{{ form.duration_scale.id_for_label }}" class="ml-3 bg-orange-200 capitalize text-gray-900 text-sm rounded-lg focus:ring-0 border-0 block w-full p-2.5" data-test="duration-select">
                    {% for value in form.duration_scale %}
                        <option value="{{ value.data.value }}"
                                class="capitalize"
                                {% if value.data.value == form.duration_scale.value %}selected{% endif %}>
                            {{ value.data.value }}s
                        </option>
                    {% endfor %}
                </select>
            </div>
            <input type="checkbox" name="is_draft" id="is_published_top" checked />
        </form>
        <!-- Add ingredients to recipe -->
        {% include "patterns/components/ingredient_form/ingredient_form.html" %}
        {% include "patterns/components/ingredient_list/ingredient_list.html" %}
        <!-- Add Recipe steps -->
        {% include "patterns/components/step_form/step_form.html" %}
        {% include "patterns/components/step_list/step_list.html" with cant_delete_step=True %}
        <!-- Add Tags -->
        {% include "patterns/components/tag_editor/tag_editor.html" %}
        <!-- Add links to recipe -->
        {% include "patterns/components/link_form/link_form.html" with content="recipe" %}
        {% include "patterns/components/link_list/link_list.html" %}
        <!-- to publish recipe -->
        {% include "patterns/components/check_box/check_box.html" with value="is_published" text="Publish recipe" %}
        <div class="w-full text-right">
            <button id="send-form"
                    class="bg-orange-800 text-white rounded-lg px-10 py-2 cursor-pointer"
                    data-test="submit">
                {% if create %}
                    Create Recipe
                {% else %}
                    Edit Recipe
                {% endif %}
            </button>
            <button id="is-sending"
                    class="bg-gray-400 text-white rounded-lg px-10 py-2 cursor-pointer hidden"
                    disabled>
                <span id="indicator-form">{% include "patterns/components/spinner/spinner.html" %}</span>
            </button>
        </div>
    </section>
    <script>
		const indicatorFull = document.getElementById("indicator-form")
		const topForm = document.getElementById("top-form")
		const isPublished = document.getElementById("is_published")
		const isPublished_top = document.getElementById("is_published_top")
		const sendForm = document.getElementById("send-form")
		const isSending = document.getElementById("is-sending")
		const reciptCategory = document.getElementById("{{ form.category.id_for_label }}")
		reciptCategory.addEventListener("change",updateBg)
		sendForm.addEventListener("click", submitForm);
		isPublished.addEventListener("change", updateIsPublished)
		function updateIsPublished(e){
			isPublished_top.checked = isPublished.checked
		}
		function submitForm(e){
			e.preventDefault()
			sendForm.classList.add("hidden")
			isSending.classList.remove("hidden")
			document.getElementById("top-form").submit();
		}
		function updateBg(e){
			console.log(reciptCategory.value)
			if (reciptCategory.value == "Recipe"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #fff 0%, #000 100%)"
			} else if (reciptCategory.value == "Health"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #eee 0%, #111 100%)"
			} else if (reciptCategory.value == "Cosmetic"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #ccc 0%, #222 100%)"
			} else if (reciptCategory.value == "Garden"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #bbb 0%, #333 100%)"
			} else if (reciptCategory.value == "Home"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #aaa 0%, #444 100%)"
			} else if (reciptCategory.value == "Fermentaion"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #999 0%, #555 100%)"
			} else if (reciptCategory.value == "Animal"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #888 0%, #666 100%)"
			} else if (reciptCategory.value == "Juice"){
				document.body.style.backgroundImage = "linear-gradient(-20deg, #777 0%, #888 100%)"
			}
		}
    </script>
    <style>
		.bg-red{
			background-image: linear-gradient(-20deg, #fff 0%, #000 100%);
		}	
    </style>
{% endblock content %}