account/urls.py
from account.views.api import (
    check_email,
    check_username,
    edit_bio,
    edit_image,
    users_detail,
    users_list,
)
from account.views.page import (
    CustomPasswordResetConfirmView,
    author_detail,
    authors,
    login_view,
    password_change_success,
    profile,
    register,
    send_password_reset_email,
    user_articles,
    user_favorites,
    user_recipes,
)
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "user"

urlpatterns = [
    # page
    path("register/", register, name="register"),
    path("profile/", profile, name="profile"),
    path("authors/", authors, name="authors"),
    path("author/<int:pk>", author_detail, name="detail"),
    path("account/", profile, name="account"),
    path("login/", login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("reset-password/", send_password_reset_email, name="password-reset"),
    path(
        "password-reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "password-change-success/",
        password_change_success,
        name="password-change-success",
    ),
    path("user/recipes", user_recipes, name="my-recipes"),
    path("user/articles", user_articles, name="my-articles"),
    path("user/favorites", user_favorites, name="my-favorites"),
    # API
    path("api/users/", users_list, name="api-user-list"),
    path("apo/users/<int:pk>", users_detail, name="api-user-detail"),
    path("check/username", check_username, name="api-validation-username"),
    path("check/email", check_email, name="api-validation email"),
    path("edit-bio/image/", edit_image, name="api-edit-image"),
    path("edit-bio/<str:field>", edit_bio, name="api-edit-bio"),
]

article/urls.py
from django.urls import path

from .views.api import article_creation, article_detail, set_favorite
from .views.page import page_article_creation, page_article_detail, page_article_edit

app_name = "article"


urlpatterns = [
    # Pages
    path("new/", page_article_creation, name="new"),
    path("edit/<int:pk>/", page_article_edit, name="edit-page"),
    path("<int:pk>/", page_article_detail, name="detail"),
    # API
    path("api/", article_creation, name="api-new"),
    path("api/<int:pk>/", article_detail, name="api-detail"),
    path("api/<int:pk>/favorite/", set_favorite, name="api-set-favorite"),
]

common/urls.py
from django.urls import path

from .views import detail_comment, link_detail, link_list, list_comment, report, tag

urlpatterns = [
    path(
        "api/comment/<int:pk>",
        detail_comment,
        name="api-detail-comment",
    ),
    path(
        "api/comment/<int:pk>/<str:content_type>",
        list_comment,
        name="api-list-comment",
    ),
    path(
        "api/links/<str:content_type>",
        link_list,
        name="api-link-list",
    ),
    path(
        "api/link/<int:pk>",
        link_detail,
        name="api-link-detail",
    ),
    path("api/report/<int:pk>/<str:content_type>", report, name="api-report"),
    path(
        "tag/<int:pk>/",
        tag,
        name="tag-detail",
    ),
]

elisasrecipe/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path

from .views.api import FeedSearchView, FeedView, health, search
from .views.page import about, cookie, index, policy, terms


def health(request):
    return JsonResponse({"status": "ok"})


urlpatterns = [
    path("admin/", admin.site.urls),
    path("health/", health, name="health"),
    # path("", include("django_backblaze_b2.urls")),
]
if settings.DEBUG:
    urlpatterns += [path("__reload__/", include("django_browser_reload.urls"))]

urlpatterns += i18n_patterns(
    path("", index, name="home"),
    path("cookie/", cookie, name="cookie"),
    path("policy/", policy, name="policy"),
    path("terms/", terms, name="terms"),
    path("about/", about, name="about"),
    path("recipes/", about, name="page-recipes"),
    path("articles/", about, name="page-articles"),
    path("authors/", about, name="page-authors"),
    path("feed/", FeedView.as_view(), name="feed"),
    path("feed/search", FeedSearchView.as_view(), name="feed-search"),
    path("api/search", search, name="api-search"),
    path("", include("account.urls")),
    path("article/", include("article.urls")),
    path("", include("common.urls")),
    path("recipe/", include("recipe.urls")),
)

recipe/urls.py
from django.urls import path
from recipe.views.api import ingredient_detail  # recipe_creation,
from recipe.views.api import (
    recipe_creation,
    ingredient_list,
    recipe_edit,
    search_recipes,
    set_favorite,
    set_rating,
    step_detail,
    step_list,
)

from .views.page import (
    page_edit_recipe,
    page_recipe_creation,
    page_recipe_detail,
    page_recipes,
    page_search_recipes,
)

app_name = "recipe"

urlpatterns = [
    # Pages
    path("", page_recipes, name="list"),
    path("new/", page_recipe_creation, name="new"),
    path("<int:pk>/", page_recipe_detail, name="detail"),
    path("<int:pk>/edit/", page_edit_recipe, name="edit"),
    # path("search/", page_search_recipes, name="search"),
    # API
    # path("api/search/", search_recipes, name="api-search"),
    path("api/list", recipe_creation, name="api-list"),
    path("api/<int:pk>/", recipe_edit, name="api-detail"),
    path("api/<int:pk>/rating/", set_rating, name="api-rating"),
    path("api/<int:pk>/favorite/", set_favorite, name="api-favorite"),
    path("api/ingredient/", ingredient_list, name="api-ingredient-list"),
    path("api/ingredient/<int:pk>/", ingredient_detail, name="api-ingredient-detail"),
    path("api/step/", step_list, name="api-step-list"),
    path("api/step/<int:pk>/", step_detail, name="api-step-detail"),
]

account/views.py
import requests
from account.models import PasswordResetToken, User
from article.models import Article
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.decorators.csrf import csrf_exempt
from django_htmx.http import HttpResponseClientRedirect, retarget
from django_htmx.middleware import HtmxDetails
from elisasrecipe import settings
from recipe.models import Recipe

from .forms import ArticleForm, ImageForm, LoginForm, ProfileForm, UserRegistrationForm


class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails


def index(request: HtmxHttpRequest) -> HttpResponse:
    return render(
        request,
        "index.html",
    )


def register(request):
    if request.htmx:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseClientRedirect("/")
        else:
            print(form.errors)
        return render(
            request,
            "components/register.html",
            {"form": form},
        )
    form = UserRegistrationForm()
    return render(
        request,
        "auth_core.html",
        {"form": form, "step": "register"},
    )


def login_view(request):
    if request.htmx:
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = User.objects.get(email=username)
            except User.DoesNotExist:
                # TODO refrsh page with error message
                return HttpResponse("user not found")
            user = authenticate(request, username=user.username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseClientRedirect(reverse("home"))
            else:
                print(form.errors)
        return render(
            request,
            "components/login.html",
            {"form": form},
        )
    form = LoginForm()
    return render(
        request,
        "auth_core.html",
        {"form": form, "step": "login"},
    )


@csrf_exempt
def check_username(request):
    if request.htmx:
        User = get_user_model()
        username = request.POST.get("username")
        if not User.objects.filter(username=username):
            return render(request, "icons/success.html")
        return render(request, "icons/cross.html")


@csrf_exempt
def check_email(request):
    if request.htmx:
        User = get_user_model()
        email = request.POST.get("email")
        if not User.objects.filter(email=email):
            return render(request, "icons/success.html")
        return render(request, "icons/cross.html")


def send_password_reset_email(request):
    if request.htmx:
        email = request.POST["email"]
        try:
            from .models import User

            user = User.objects.get(email=email)

        except User.DoesNotExist:
            rest = render(request, "responses/email_not_found.html")
            return retarget(rest, "#validation-mail-sent")
        token_generator = default_token_generator
        token = token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))

        PasswordResetToken.objects.create(user=user, token=token)

        current_site = get_current_site(request)
        mail_subject = "Reset your password"
        intro = (
            f"Hi {user.username},\n\nTo reset your password, click the link below:\n\n"
        )
        api_key = settings.APIKEY_MAILWIND
        link = f"{current_site}/password-reset/{uid}/{token}/\n\n"
        print(f"{link=}")
        content = render_to_string(
            "emails/password_forgot.html", {"intro": intro, "link": link}
        )
        headers = {"Authorization": "Bearer " + api_key}
        payload = {
            "sender": {"name": "Yohann", "email": "yohann@ymepa.me"},
            "Destinations": [{"email": "yoyo.mepa@gmail.com", "type": "to"}],
            "Subject": mail_subject,
            "Code": content,
        }
        resp = requests.post(
            "https://api.mailwind.io/v1/send", headers=headers, json=payload
        )
        print(resp.status_code)
        return render(
            request, "responses/email_sent.html", {"intro": intro, "link": link}
        )
    else:
        return render(request, "auth_core.html", {"step": "reset-password"})


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "components/change_password.html"
    post_reset_login = True
    success_url = reverse_lazy("password-change-success")


def password_change_success(request):
    return render(request, "components/password_change_success.html")


@csrf_exempt
def delete_users(request):
    if request.method == "DELETE":
        prefix = "pw_test_"
        users = User.objects.filter(username__startswith=prefix)
        count, _ = users.delete()
        return JsonResponse({"message": f"{count} users deleted."})
    else:
        return JsonResponse({"message": "Invalid request method."}, status=405)


def get_user_reset_token(request, user_email):
    if settings.DEBUG:
        user = User.objects.get(email=user_email)
        token = PasswordResetToken.objects.get(user=user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        return JsonResponse({"token": token.token, "uid": uid})
    return HttpResponse("Endpoint Not for production", status=404)


def profile(request):
    user = request.user
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
    else:
        form = ProfileForm(instance=user)
    return render(
        request,
        "profile.html",
        {"form": form, "user": user},
    )


def edit_bio(request, field):
    if request.htmx:
        user = request.user
        if field == "first-name":
            if request.GET.get("first-name"):
                user.first_name = request.GET.get("first-name")
            args = {
                "label": "First Name",
                "value": user.first_name,
                "empty_css_class": "first_name_empty",
                "input_css_class": "first_name_input",
            }
        elif field == "image":
            if request.GET.get("first-name"):
                user.first_name = request.GET.get("first-name")
            args = {
                "label": "First Name",
                "value": user.first_name,
                "empty_css_class": "first_name_empty",
                "input_css_class": "first_name_input",
            }
        elif field == "last-name":
            if request.GET.get("last-name"):
                user.last_name = request.GET.get("last-name")
            args = {
                "label": "Last Name",
                "value": user.last_name,
                "empty_css_class": "last_name_empty",
                "input_css_class": "last_name_input",
            }
        elif field == "bio":
            if request.GET.get("bio"):
                user.bio = request.GET.get("bio")
            args = {
                "label": "Bio",
                "value": user.bio,
                "empty_css_class": "bio_empty",
                "input_css_class": "bio_input",
            }
        user.save()
    return render(
        request,
        "components/editable_field.html",
        args,
    )


def authors(request):
    users = User.objects.all()
    return render(
        request,
        "authors.html",
        {"authors": users},
    )


def search_authors(request):
    if request.htmx:
        query = request.GET.get("query")
        users = User.objects.filter(username__icontains=query)
        return render(
            request,
            "components/authors_search_results.html",
            {"authors": users},
        )
    return HttpResponse("Endpoint Not for production", status=404)


def user_recipes(request):
    recipes = Recipe.objects.filter(author=request.user)
    return render(
        request,
        "recipe_user_list.html",
        {
            "recipes": recipes,
        },
    )


@login_required
def user_favorites(request):
    recipes = User.favorite_recipes
    return render(
        request,
        "recipe_user_list.html",
        {
            "recipes": recipes,
        },
    )


def user_articles(request):
    form = ArticleForm()
    articles = Article.objects.filter(author=request.user)
    return render(
        request,
        "user_articles.html",
        {"articles": articles, "onwer": True, "form": form},
    )


def edit_image(request):
    if request.htmx:
        print(request.FILES)
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.save()
            print("img")
            print(img)
            user = request.user
            user.profile_picture = img
            user.save()
        return """
                <p>image saved</p>
            """
    print(7)
    return HttpResponse("Endpoint for htmx")

account/templates/article_detail.html
{% extends "base.html" %}
{% load static %}
{% load my_filters %}
{% block extra_head %}
    {% include "components/import_quill.html" %}
    {% include "components/import_sweetalert.html" %}
    <script src="{% static 'htmx.min.js' %}" defer></script>
{% endblock extra_head %}
{% block content %}
    {% include "navbar.html" %}
    <div class="flex items-center justify-center ">
        <div class=" mx-auto my-24 w-2/3 bg-orange-50 overflow-hidden rounded-lg">
            <div class="sm:block hidden h-52 overflow-hidden mb-5 bg-cover bg-center w-full"
                 style="background-image: url('{{ article.image.image.crop.600x200.url|minio_to_localhost }}')"></div>
            <div class="sm:hidden block h-52 overflow-hidden mb-5 bg-cover bg-center w-full"
                 style="background-image: url('{{ article.image.image.crop.400x400.url|minio_to_localhost }}')"></div>
                 <div class="flex">
                    {% for link in links %}
                        {% include 'components/link.html' %}
                    {% endfor %}
                </div>
            {% url 'article:edit-page' pk=article.id as article_edit %}
            {% if user.is_authenticated %}
                {% if request.user == recipe.author %}
                    {% include "btn.html" with url=article_edit link_text="🖊️ Edit the article" dataTest="edit-article" %}
                {% endif %}
            {% endif %}
            {% if user.is_authenticated %}
                <div class="float-right pr-10">
                    <!-- report -->
                    {% url 'api-report' pk=article.id content_type="article" as url %}
                    {% include "patterns/components/reportter/report.html" with url=url content_type="article" id=article.id %}
                </div>
            {% endif %}
            <div class="px-10 pt-7">
                <div class="cursor-pointer pb-3">
                    <button hx-get="{% url "article:api-set-favorite" pk=article.id %}"
                            hx-trigger="click"
                            hx-target="#is-fav">{% include "is_favorite.html" %}</button>
                </div>
                <div class="mb-8 no-tailwind all-initial remove-all">
                    <p class="text-7xl font-semibold capitalize">{{ article.title }}</p>
                    <div class="quill-content ml-3 mt-4">
                        {% autoescape off %}
                            {{ article.content.html|safe }}
                        {% endautoescape %}
                    </div>
                </div>

                <!-- comment -->
                {% if comment is not empty %}
                    <div class="py-4 " id="comments">
                        <p class="text-xl first-letter:uppercase font-thin first-letter:italic">Comments:</p>
                        {% include "comments.html" %}
                    </div>
                {% endif %}
                {% include "components/tag_list.html" %}
                {% include "comment_list.html" %}
                {% if user.is_authenticated %}
                    {% include "patterns/components/comment_form/comment_form.html" with pk=article.id content_type="Article" comment_form=comment_form %}
                {% else %}
                    <p>
                        <a href="{% url 'user:login' %}">Log in</a> to add a comment.
                    </p>
                {% endif %}
                {% if request.user == article.author %}
                    <div class="w-full">
                        <!-- delete -->
                        {% url 'article:api-detail' pk=article.id as url %}
                        {% include "patterns/components/deletter/delete.html" with content_type="article" url=url %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <style>
        @charset "UTF-8";
        .article-img
        {
            background: url('{{ article.image.image.url }}');
            background-size: cover;
            background-position: center;
        }
    </style>
{% endblock content %}

account/templates/auth_core.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block extra_head %}
    <script src="{% static 'htmx.min.js' %}" defer></script>
{% endblock extra_head %}
{% block content %}
    <div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
        <div class="relative py-3 sm:max-w-xl sm:mx-auto">
            <div class="absolute inset-0 bg-gradient-to-r from-orange-300 to-orange-600 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl">
            </div>
            <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
                <div class="max-w-md mx-auto">
                    <div class="w-full text-center mx-auto">
                        <h1 class="text-4xl font-semibold text-orange-600 tracking-wide pb-10">
                            {% if step == "login" %}
                                {% translate "log-page-title" %}
                            {% elif step == "register" %}
                                {% translate 'register-page-title' %}
                            {% elif step == "reset-password" %}
                                {% translate 'password-forgot-title' %}
                            {% endif %}
                        </h1>
                    </div>
                    <div class="divide-y divide-gray-200">
                        <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
                            <form id="form"
                                  {% if step == "login" %}
                                      hx-post="{% url 'user:login' %}"
                                  {% elif step == "register" %}
                                      hx-post="{% url 'user:register' %}"
                                  {% elif step == "reset-password" %}
                                      hx-post="{% url 'user:password-reset' %}"
                                  {% endif %}
                                  hx-target="#form-holder"
                                  hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
                                <div id="form-holder">
                                    {% if step == "login" %}
                                        {% include 'components/login.html' %}
                                    {% elif step == "register" %}
                                        {% include 'components/register.html' %}
                                    {% elif step == "reset-password" %}
                                        {% include 'components/reset_password.html' %}
                                    {% endif %}
                                </div>
                                <div class="relative w-full text-center mx-auto mt-10">
                                    <button id="submit"
                                            type="submit"
                                            data-test="submit"
                                            class="bg-orange-500 hover:bg-orange-800 text-white rounded-md px-10 py-1 mt-5 text-center mx-auto">
                                        {% translate 'submit' %}
                                    </button>
                                    <button id="loader"
                                            type="submit"
                                            data-test="loader"
                                            class="bg-slate-300 text-white rounded-md px-10 py-1 mt-5 text-center mx-auto"
                                            disabled
                                            style="display: none">
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             width="2em"
                                             height="2em"
                                             viewBox="0 0 24 24"
                                             ...
                                             props>
                                            <circle cx="4" cy="12" r="3" fill="currentColor"><animate id="svgSpinners3DotsScale0" attributeName="r" begin="0;svgSpinners3DotsScale1.end-0.25s" dur="0.75s" values="3;.2;3" /></circle><circle cx="12" cy="12" r="3" fill="currentColor"><animate attributeName="r" begin="svgSpinners3DotsScale0.end-0.6s" dur="0.75s" values="3;.2;3" /></circle><circle cx="20" cy="12" r="3" fill="currentColor"><animate id="svgSpinners3DotsScale1" attributeName="r" begin="svgSpinners3DotsScale0.end-0.45s" dur="0.75s" values="3;.2;3" /></circle>
                                        </svg>
                                    </button>
                                </div>
                                <script>
                                    document.body.addEventListener('configRequest.htmx', (event) => {
                                        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
                                    })
                                </script>
                            </form>
                        </div>
                    </div>
                </div>
                    {% if step == "login" %}
                    <a href="{% url 'user:register' %}"
                    class="text-orange-500 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium">{% translate 'register-page-title' %}</a>
                    {% elif step == "register" %}
                    <a href="{% url 'user:login' %}"
                    class="text-orange-500 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium">{% translate "log-page-title" %}</a>
                    {% endif %}
            </div>
        </div>
    </div>
    <div class="text-center items-end text-orange-500 font-bold text-xl underline hover:text-orange-700 -mt-14">
        <a href="{% url 'home' %}">- {% translate "home-page" %} -</a>
    </div>
    <script>
        const submit = document.getElementById("submit")
        const loader = document.getElementById("loader")
        console.log(submit)
        console.log(loader)
        submit.addEventListener("click", function(event) {
            console.log("clicked")
            submit.style.display = "none";
            loader.style.display = "block";
        });
        document.addEventListener("htmx:afterSwap", function(event) {
            submit.style.display = "block";
            loader.style.display = "none";
        });
    </script>
{% endblock content %}

account/templates/authors.html
{% extends "base.html" %}
{% block content %}
    {% include "navbar.html" %}
    <section class="pt-20">
        {% include "searchbar.html" with type="author" %}
        <div class="flex flex-wrap pt-36 items-center justify-center px-10">{% include "components/author_list.html" %}</div>
    </section>
{% endblock content %}

account/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
    {% include "components/import_quill.html" %}
    {% include "components/import_tagify.html" %}
    {% include "components/import_sweetalert.html" %}
    <script src="{% static 'htmx.min.js' %}" defer></script>
{% endblock extra_head %}
{% block content %}
    <div class="flex ">
        {% include "components/profile_navbar.html" %}
        <div class="bg-white pl-10 pt-20 w-full">
            <div class="flex justify-center py-2 text-orange-700 title-profile text-5xl">Edit your profile</div>
            <div class="flex mt-24">
                <div class="w-5/6 ">
                    <div class="bg-orange-400 rounded-lg ml-10  text-white shadow">
                        <div class="absolute">
                            {% include "components/editable_image.html" with details="profile" img=user.profile_picture.image.crop.400x400.url %}
                        </div>
                        <div class="ml-44 py-10 ">
                            <div class="ml-5 text-white">
                                <p>
                                    <span class="font-thin capitalize italic">Username:</span>
                                    <span class="font-bold capitalize ">{{ user.username }}</span>
                                </p>
                                <p>
                                    <span class="font-thin capitalize italic">email:</span>
                                    <span class="font-bold  ">{{ user.email }}</span>
                                </p>
                                {% include "components/editable_field.html" with label="First Name" value=user.first_name empty_css_class="first_name_empty" input_css_class="first_name_input" %}
                                {% include "components/editable_field.html" with label="Last Name" value=user.last_name empty_css_class="last_name_empty" input_css_class="last_name_input" %}
                                {% include "components/editable_field.html" with label="Bio" value=user.bio empty_css_class="bio_empty" input_css_class="bio_input" %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include "patterns/components/link_form/link_form.html" with content="user" %}
            {% include "patterns/components/link_list/link_list.html" %}    
            <div class="w-4/5 py-10 ml-10">
                {% url 'article:new' as article_new %}
                {% url 'recipe:new' as recipe_new %}
                <div class="float-left">{% include "btn.html" with url=article_new link_text="Create Article" %}</div>
                <div class="float-right">{% include "btn.html" with url=recipe_new link_text="Create recipe" %}</div>
            </div>
            <div class="w-full  text-right px-10 pt-20">
                <button id="delete-button"
                        hx-delete="{% url "user:api-user-detail" pk=user.pk %}"
                        data-test="delete-account"
                        {% comment %} hx-confirm="delete" {% endcomment %}
                        class="border-2 border-red-500 px-10 py-2 rounded-lg text-red-600 hover:text-white hover:border-0 hover:bg-red-600">
                    Delete account
                </button>
            </div>
        </div>
    </div>
    <style>
        .title-profile{
            font-family: 'Poppins', serif;
        }
    </style>
    <script>
        const deleteInput = "I want to delete"
        const deleteButton = document.getElementById("delete-button")
        deleteButton.addEventListener("htmx:confirm", async function(e) {
            e.preventDefault()
            Swal.fire({
                icon: "error",
                showCancelButton: true,
                title: "Input email address",
                input: "text",
                inputAttributes: {
                    "data-test": "delete-input",
                },
                html: `to delete your account type: <b>${deleteInput}</b>`,
                inputPlaceholder: deleteInput
            }).then(function(result) {
                e.detail.issueRequest(false)
                if(result.isConfirmed){
                    if(result.value == deleteInput){
                        Swal.fire(" Account Delete!", "", "success");
                    } else if (result.isDenied) {
                        Swal.fire("String don't match", "", "info");
                    }
                } else if (result.isDenied) {
                    Swal.fire("Account not Deleted", "", "info");
                }
            })
        })
    </script>
{% endblock content %}